/**
 * Procedural starfield cubemap → public/assets/env/
 * Run: npm run assets:skybox
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public/assets/env');
mkdirSync(outDir, { recursive: true });

const SIZE = 512;
const FACES = ['px', 'nx', 'py', 'ny', 'pz', 'nz'];

function mulberry32(seed) {
  return () => {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function faceSeed(name) {
  let h = 2166136261;
  for (let i = 0; i < name.length; i += 1) {
    h ^= name.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

async function bakeFace(name) {
  const rand = mulberry32(faceSeed(name));
  const buf = Buffer.alloc(SIZE * SIZE * 3);

  // Deep space base + subtle nebula gradient.
  for (let y = 0; y < SIZE; y += 1) {
    for (let x = 0; x < SIZE; x += 1) {
      const i = (y * SIZE + x) * 3;
      const nx = x / SIZE;
      const ny = y / SIZE;
      const nebula = 0.5 + 0.5 * Math.sin(nx * 4.2 + ny * 2.1) * Math.cos(ny * 3.3 - nx);
      const glow = Math.max(0, nebula - 0.35) * 18;
      buf[i] = Math.min(255, 4 + glow * 0.35);
      buf[i + 1] = Math.min(255, 6 + glow * 0.45);
      buf[i + 2] = Math.min(255, 14 + glow * 0.9);
    }
  }

  const starCount = 900;
  for (let s = 0; s < starCount; s += 1) {
    const x = Math.floor(rand() * SIZE);
    const y = Math.floor(rand() * SIZE);
    const bright = 140 + Math.floor(rand() * 115);
    const radius = rand() > 0.92 ? 1 : 0;
    for (let dy = -radius; dy <= radius; dy += 1) {
      for (let dx = -radius; dx <= radius; dx += 1) {
        const px = x + dx;
        const py = y + dy;
        if (px < 0 || py < 0 || px >= SIZE || py >= SIZE) continue;
        const i = (py * SIZE + px) * 3;
        const fall = radius === 0 ? 1 : 1 - (Math.abs(dx) + Math.abs(dy)) * 0.35;
        buf[i] = Math.min(255, buf[i] + bright * fall);
        buf[i + 1] = Math.min(255, buf[i + 1] + bright * fall);
        buf[i + 2] = Math.min(255, buf[i + 2] + bright * fall * 0.95);
      }
    }
  }

  const outPath = join(outDir, `${name}.png`);
  await sharp(buf, { raw: { width: SIZE, height: SIZE, channels: 3 } })
    .png()
    .toFile(outPath);
  console.warn(`wrote env/${name}.png`);
}

async function main() {
  for (const face of FACES) {
    await bakeFace(face);
  }
  writeFileSync(
    join(outDir, 'CREDITS.txt'),
    'Procedural starfield cubemap generated by scripts/bakeSpaceSkybox.mjs\n',
  );
  console.warn('Done. Space skybox faces written.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
